# Generated by Django 4.2.13 on 2024-06-21 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_api', '0004_alter_log_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='changes',
        ),
        migrations.AddField(
            model_name='product',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.IntegerField(choices=[(1, 'Added product'), (2, 'Updated product'), (3, 'Deleted product')]),
        ),
    ]
