# Generated by Django 4.2.13 on 2024-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_api', '0005_remove_log_changes_product_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='changes',
            field=models.TextField(blank=True),
        ),
    ]
