# Generated by Django 4.2.13 on 2024-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_api', '0006_log_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.IntegerField(choices=[(1, 'Added product'), (2, 'Updated product')]),
        ),
    ]
